In [ ]:
#IMPORTING LIBRARIES
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

In [2]:
#IMPORTING DATASETS
dataset = pd.read_csv('diabetes_prediction_dataset.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [3]:
#ENCODING CATEGORICAL DATA
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
t = ColumnTransformer(transformers=[('encoders',OneHotEncoder(),[0]+[4])],remainder='passthrough')
X=np.array(t.fit_transform(X))

In [11]:
print(X)

[[1.0 0.0 0.0 ... 25.19 6.6 140]
 [1.0 0.0 0.0 ... 27.32 6.6 80]
 [0.0 1.0 0.0 ... 27.32 5.7 158]
 ...
 [0.0 1.0 0.0 ... 27.83 5.7 155]
 [1.0 0.0 0.0 ... 35.42 4.0 100]
 [1.0 0.0 0.0 ... 22.43 6.6 90]]


In [12]:
print(y)

[0 0 0 ... 0 0 0]


In [4]:
#SPLITTING TH DATASET INTO TEST SET AND TRAINING SET
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [13]:
print(X_train)

[[1.0 0.0 0.0 ... 31.48 4.5 100]
 [1.0 0.0 0.0 ... 24.7 6.1 80]
 [1.0 0.0 0.0 ... 27.32 6.6 100]
 ...
 [0.0 1.0 0.0 ... 41.23 9.0 145]
 [1.0 0.0 0.0 ... 30.18 5.8 90]
 [1.0 0.0 0.0 ... 27.32 4.5 158]]


In [14]:
print(X_test)

[[1.0 0.0 0.0 ... 27.32 4.8 140]
 [0.0 1.0 0.0 ... 27.32 4.8 100]
 [1.0 0.0 0.0 ... 37.16 6.6 85]
 ...
 [1.0 0.0 0.0 ... 27.32 4.0 130]
 [0.0 1.0 0.0 ... 25.93 3.5 126]
 [1.0 0.0 0.0 ... 27.32 6.6 159]]


In [15]:
print(y_train)

[0 0 0 ... 1 0 0]


In [16]:
print(y_test)

[0 0 0 ... 0 0 1]


In [5]:
#FEATURE SCALING
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train[:,5:8]= sc.fit_transform(X_train[:,5:8])
X_test[:,5:8] = sc.transform(X_test[:,5:8])

In [6]:
#TRAINING THE MODEL ON LOGISTIC REGRESSION MODEL
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)
classifier.fit(X_train[:,], y_train)

C:\Users\panig\anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(random_state=0)

In [7]:
#PREDICTING RESULTS
y_pred = classifier.predict(X_test)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 0]
 [0 0]
 ...
 [0 0]
 [0 0]
 [1 1]]


In [10]:
#MAKING THE CONFUSION MATRIX
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)


[[22687   208]
 [ 1122   983]]


0.9468